# Generated by Django 5.2.4 on 2025-09-14 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='ชื่อร้านค้า')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='อีเมลติดต่อ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(verbose_name='ที่อยู่ร้านค้า')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='entrepreneur_profiles/', verbose_name='รูปโปรไฟล์ร้านค้า')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
