# Generated by Django 5.2.4 on 2025-09-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Dog', 'สุนัข'), ('Cat', 'แมว')], default='Dog', max_length=10),
        ),
    ]
