# Generated by Django 5.2.4 on 2025-09-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0002_entrepreneur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrepreneur',
        ),
    ]
