# Generated by Django 5.2.4 on 2025-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0003_delete_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='คุณสมบัติสินค้า (กรอกเอง)', null=True),
        ),
    ]
