# Generated by Django 5.2.4 on 2025-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0006_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนสินค้าคงเหลือ'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนสินค้าทั้งหมด'),
        ),
    ]
