# Generated by Django 5.2.4 on 2025-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0012_add_entrepreneur_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, choices=[('dog', 'สุนัข'), ('cat', 'แมว')], help_text='สำหรับหมวดอาหาร: ประเภทสัตว์ (สุนัข/แมว)', max_length=10, null=True),
        ),
    ]
