# Generated by Django 5.2.4 on 2025-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0018_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
