# Generated by Django 5.2.4 on 2025-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0019_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='bank_book_copy',
            field=models.ImageField(blank=True, null=True, upload_to='bankbooks/'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='id_card_copy',
            field=models.ImageField(blank=True, null=True, upload_to='idcards/'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('preparing', 'กำลังเตรียมสินค้า'), ('delivering', 'กำลังจัดส่ง'), ('success', 'สำเร็จ')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, choices=[('dog', 'สุนัข'), ('cat', 'แมว')], help_text='สำหรับหมวดอาหาร: ประเภทสัตว์', max_length=10, null=True),
        ),
    ]
