# Generated by Django 5.2.4 on 2025-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0020_entrepreneur_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='entrepreneur',
        ),
        migrations.AddField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('preparing', 'กำลังเตรียมของ'), ('delivering', 'กำลังจัดส่ง'), ('success', 'สำเร็จ'), ('cancel', 'ยกเลิก')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
