# Generated by Django 5.2.4 on 2025-12-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_unread_status_update',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
