# Generated by Django 5.2.4 on 2026-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0031_chatmessage_attachment_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
