# Generated by Django 5.2.4 on 2026-01-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0032_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20),
        ),
    ]
