# Generated by Django 5.2.4 on 2026-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0033_entrepreneur_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='commerce_doc',
            field=models.ImageField(blank=True, null=True, upload_to='commerce_docs/'),
        ),
    ]
