# Generated by Django 5.2.4 on 2026-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0034_entrepreneur_commerce_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='ค่าจัดส่งเหมาจ่ายของร้าน', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
