# Generated by Django 5.2.4 on 2026-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0035_entrepreneur_shipping_cost_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hidden_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='hidden_by_entrepreneur',
            field=models.BooleanField(default=False),
        ),
    ]
