# Generated by Django 5.2.4 on 2026-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0036_chatroom_hidden_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
