# Generated by Django 5.2.4 on 2026-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0039_order_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_reason',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('preparing', 'กำลังเตรียมของ'), ('delivering', 'กำลังจัดส่ง'), ('success', 'สำเร็จ')], default='waiting', max_length=20),
        ),
    ]
