# Generated by Django 5.2.4 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0040_remove_order_cancel_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='เหตุผลที่ยกเลิกคำสั่งซื้อ', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('preparing', 'กำลังเตรียมของ'), ('delivering', 'กำลังจัดส่ง'), ('success', 'สำเร็จ'), ('canceled', 'ยกเลิก')], default='waiting', max_length=20),
        ),
    ]
