# Generated by Django 5.2.4 on 2026-02-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0045_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
