# Generated by Django 5.2.4 on 2026-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0047_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return_requested',
            field=models.BooleanField(default=False, help_text='ลูกค้ากดขอคืนสินค้าแล้วหรือไม่'),
        ),
    ]
