# Generated by Django 5.2.4 on 2026-04-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0048_order_is_return_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
