# Generated by Django 5.2.4 on 2026-05-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petjoy', '0049_reviewreply_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
